/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#dfe2eb",
        "secondary": "#fbabff",
        "surface-subtle": "#161B22",
        "secondary-fixed-dim": "#fbabff",
        "outline": "#8b919d",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#4f3400",
        "tertiary-container": "#da9600",
        "surface-container-lowest": "#0a0e14",
        "surface-border": "#30363D",
        "surface-dim": "#10141a",
        "error": "#ffb4ab",
        "surface-container-highest": "#31353c",
        "inverse-primary": "#0060aa",
        "on-primary-fixed-variant": "#004882",
        "surface-container": "#1c2026",
        "on-primary-fixed": "#001c38",
        "on-error": "#690005",
        "inverse-on-surface": "#2d3137",
        "surface-container-low": "#181c22",
        "primary-container": "#58a6ff",
        "primary-fixed": "#d3e4ff",
        "tertiary-fixed-dim": "#ffba42",
        "surface-tint": "#a2c9ff",
        "on-secondary": "#580065",
        "text-muted": "#8B949E",
        "on-background": "#dfe2eb",
        "surface-variant": "#31353c",
        "background": "#0D1117",
        "bullish": "#4ADE80",
        "on-secondary-fixed": "#36003e",
        "outline-variant": "#414752",
        "tertiary-fixed": "#ffddaf",
        "surface": "#10141a",
        "secondary-fixed": "#ffd6fd",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#614000",
        "on-secondary-fixed-variant": "#7c008e",
        "on-surface-variant": "#c0c7d4",
        "tertiary": "#ffba42",
        "primary": "#a2c9ff",
        "on-secondary-container": "#ffd8fd",
        "on-surface": "#dfe2eb",
        "primary-fixed-dim": "#a2c9ff",
        "on-tertiary": "#432c00",
        "on-primary": "#00315c",
        "surface-bright": "#353940",
        "bearish": "#F87171",
        "on-primary-container": "#003a6b",
        "on-tertiary-fixed": "#281800",
        "secondary-container": "#ae05c6",
        "surface-container-high": "#262a31"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "16px",
        "container-max": "1440px",
        "unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px"
      },
      "fontFamily": {
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "data-tabular": ["13px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-caps": ["11px", {"lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
